config/routes.rb
Rails.application.routes.draw do
  
  resources :conversations, only: [:show]
  
  get 'chat', to: 'conversations#retrieve_conversation', as: 'chat'
  
  post 'reminder', to: 'emails#reminder', as: 'reminder'
  
  post 'update_rating', to: 'saved_links#update_rating', as: 'update_rating'
  
  resources :saved_links, only: [:index]

  get 'update_link', to: 'saved_links#update_link', as: 'update_link'
  
  get 'posts/test'

  get 'posts/test_yaml'

  resources :appointments

  get "my_clients", to: 'appointments#my_clients', as: 'my_clients'
  get 'my_appointments', to: 'appointments#my_appointments', as: 'my_appointments'

  get 'search', to: 'search#results', as: 'search'

  get 'contact/new'

  post 'contact/send_email'

  post 'tokens' => "tokens#create"

  get 'my_answers', to: 'answers#my_answers', as: 'my_answers'

  resources :messages

  resources :answers

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :posts

  get 'my_posts', to: 'posts#my_posts', as: 'my_posts'

 get 'auth/:provider/callback', to: 'sessions#create'

 get 'sign_out', to: 'sessions#destroy', as: 'sign_out'

 post 'send', to: 'messages#email_message', as: 'mail'

  root 'posts#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
# realtionships
belongs_to :user
belongs_to :consultant, class_name: "User"


 validates :name, presence: true
 validates :email, presence: true
 validates :time, presence: true
 validates_uniqueness_of :time
 
  
  

  def start_time
  	time
  end
 
 # get all the appointments for the following day
 def self.following_day_appointments
  all.where("time >= ?", (Time.now + 3.hours))
 end

end

app/models/chat_message.rb
class ChatMessage < ActiveRecord::Base
  # associations
  belongs_to :conversation
  belongs_to :user
  
  #life cycle hook
  after_create_commit { ChatMessageBroadcastJob.perform_later self }
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  	#associations
  	belongs_to :user
  	belongs_to :consultant, class_name: "User"
  	has_many :chat_messages, dependent: :destroy
  	
  	#validations
  	validates_uniqueness_of :user_id, scope: :consultant_id
  	
end

app/models/data.rb
require 'result'
class Data
	def self.parse(results)
		result_set = []
		results.items.each do |result|
			
			# item = SavedLink.find_by_link_url(result.link.to_s) ? SavedLink.find_by_link_url(result.link.to_s) : Result.new(result.title, result.link.to_s)
			if SavedLink.find_by_link_url(result.link.to_s)
				link = SavedLink.find_by_link_url(result.link.to_s)
				item = Result.new(link.title, link.link_url, link.click_count, link.average_rating, link.ratings.count.to_i)
				result_set << item
			else
				item = Result.new(result.title.to_s, result.link.to_s)
				result_set << item
			end
		end
		result_set # return the result set
	end
	
	def self.sort(results)
		results.sort_by! {|object| [object.average_rating, object.number_of_ratings, object.click_count] }
		results.reverse!
	end
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :description, presence: true
	
    belongs_to :user
    has_many :answers

end

app/models/rating.rb
class Rating < ActiveRecord::Base
    belongs_to :saved_link
    
    VALUES = [1, 2, 3, 4, 5]
end

app/models/result.rb
require 'data'
class Result
	attr_accessor :title, :link_url, :click_count, :average_rating, :number_of_ratings

	def initialize(title, link_url, click_count = 0, average_rating = 0, number_of_ratings = 0)
		@title = title
		@link_url = link_url
		@click_count = click_count
		@average_rating = average_rating
		@number_of_ratings = number_of_ratings
	end
end

app/models/saved_link.rb
class SavedLink < ActiveRecord::Base
    has_many :ratings
    
    def sum_of_ratings
        ratings.pluck(:rating).inject(0) {|sum, number| sum += number}
    end
    
    def average_rating
        sum_of_ratings/ratings.count.to_d
    end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	has_many :answers
	has_many :appointments
	has_many :clients, class_name: "Appointment", foreign_key: "consultant_id" 
	has_many :conversations
	has_many :chat_messages

	ROLES = ["admin", "consultant", "user"]

	def self.create_with_omniauth(auth)
		create! do |user|
		user.provider = auth["provider"]
		user.uid = auth["uid"]
		user.name = auth["info"]["name"]
		user.email = auth["info"]["email"]
		end
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def email_message
    ExampleMailer.sample_mailer.deliver
    redirect_to posts_path, notice: "Mail sent"
  end

  def index
    @messages = Message.all
    respond_with(@messages)
  end

  def show
    respond_with(@message)
  end

  def new
    if params[:send_to]
      @send_to = params[:send_to]
    end
    @message = Message.new
    respond_with(@message)
  end

  def edit
  end

  def create
    @message = Message.new(message_params)
    
    @message.save 
    respond_with(@message)
  end

  def update
    @message.update(message_params)
    respond_with(@message)
  end

  def destroy
    @message.destroy
    respond_with(@message)
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/messages/_form.html.erb
 <div class="form-style-9">
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.body %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<p><%= @send_to %></p>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

<br />

<%= button_to 'Send message', mail_path, class: "small button round" %>