config/routes.rb
Rails.application.routes.draw do
  
  resources :conversations, only: [:show]
  
  get 'chat', to: 'conversations#retrieve_conversation', as: 'chat'
  
  post 'reminder', to: 'emails#reminder', as: 'reminder'
  
  post 'update_rating', to: 'saved_links#update_rating', as: 'update_rating'
  
  resources :saved_links, only: [:index]

  get 'update_link', to: 'saved_links#update_link', as: 'update_link'
  
  get 'posts/test'

  get 'posts/test_yaml'

  resources :appointments

  get "my_clients", to: 'appointments#my_clients', as: 'my_clients'
  get 'my_appointments', to: 'appointments#my_appointments', as: 'my_appointments'

  get 'search', to: 'search#results', as: 'search'

  get 'contact/new'

  post 'contact/send_email'

  post 'tokens' => "tokens#create"

  get 'my_answers', to: 'answers#my_answers', as: 'my_answers'

  resources :messages

  resources :answers

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :posts

  get 'my_posts', to: 'posts#my_posts', as: 'my_posts'

 get 'auth/:provider/callback', to: 'sessions#create'

 get 'sign_out', to: 'sessions#destroy', as: 'sign_out'

 post 'send', to: 'messages#email_message', as: 'mail'

  root 'posts#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
# realtionships
belongs_to :user
belongs_to :consultant, class_name: "User"


 validates :name, presence: true
 validates :email, presence: true
 validates :time, presence: true
 validates_uniqueness_of :time
 
  
  

  def start_time
  	time
  end
 
 # get all the appointments for the following day
 def self.following_day_appointments
  all.where("time >= ?", (Time.now + 3.hours))
 end

end

app/models/chat_message.rb
class ChatMessage < ActiveRecord::Base
  # associations
  belongs_to :conversation
  belongs_to :user
  
  #life cycle hook
  after_create_commit { ChatMessageBroadcastJob.perform_later self }
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  	#associations
  	belongs_to :user
  	belongs_to :consultant, class_name: "User"
  	has_many :chat_messages, dependent: :destroy
  	
  	#validations
  	validates_uniqueness_of :user_id, scope: :consultant_id
  	
end

app/models/data.rb
require 'result'
class Data
	def self.parse(results)
		result_set = []
		results.items.each do |result|
			
			# item = SavedLink.find_by_link_url(result.link.to_s) ? SavedLink.find_by_link_url(result.link.to_s) : Result.new(result.title, result.link.to_s)
			if SavedLink.find_by_link_url(result.link.to_s)
				link = SavedLink.find_by_link_url(result.link.to_s)
				item = Result.new(link.title, link.link_url, link.click_count, link.average_rating, link.ratings.count.to_i)
				result_set << item
			else
				item = Result.new(result.title.to_s, result.link.to_s)
				result_set << item
			end
		end
		result_set # return the result set
	end
	
	def self.sort(results)
		results.sort_by! {|object| [object.average_rating, object.number_of_ratings, object.click_count] }
		results.reverse!
	end
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :description, presence: true
	
    belongs_to :user
    has_many :answers

end

app/models/rating.rb
class Rating < ActiveRecord::Base
    belongs_to :saved_link
    
    VALUES = [1, 2, 3, 4, 5]
end

app/models/result.rb
require 'data'
class Result
	attr_accessor :title, :link_url, :click_count, :average_rating, :number_of_ratings

	def initialize(title, link_url, click_count = 0, average_rating = 0, number_of_ratings = 0)
		@title = title
		@link_url = link_url
		@click_count = click_count
		@average_rating = average_rating
		@number_of_ratings = number_of_ratings
	end
end

app/models/saved_link.rb
class SavedLink < ActiveRecord::Base
    has_many :ratings
    
    def sum_of_ratings
        ratings.pluck(:rating).inject(0) {|sum, number| sum += number}
    end
    
    def average_rating
        sum_of_ratings/ratings.count.to_d
    end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	has_many :answers
	has_many :appointments
	has_many :clients, class_name: "Appointment", foreign_key: "consultant_id" 
	has_many :conversations
	has_many :chat_messages

	ROLES = ["admin", "consultant", "user"]

	def self.create_with_omniauth(auth)
		create! do |user|
		user.provider = auth["provider"]
		user.uid = auth["uid"]
		user.name = auth["info"]["name"]
		user.email = auth["info"]["email"]
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :provider, :uid, :role, :email)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
   <div class="field">
    <%= f.label :role %><br>
    <%= f.select :role, User::ROLES %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th class="col-md-2">Name</th>
      <th class="col-md-3">Provider</th>
      <th class="col-md-3">Uid</th>
      <th class="col-md-2">Role</th>
      <th class="col-md-2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.provider %></td>
        <td><%= user.uid %></td>
        <td><%= user.role %></td>
        <td>
        <ul>
        <li><%= link_to 'Show', user %></li>
        <li><%= link_to 'Edit', edit_user_path(user)%></li>
        <li><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="form-style-10">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @user.provider %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @user.uid %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>



<h3>Welcome <%= @user.email %> </h3>
 
<h4><%= link_to 'Sign out', sign_out_path %></h4>
 
<div class="row">
 <div class="col-md-8">
   <div id="messages"></div>
   <input id="chat-input" class="form-control" type="text" placeholder="say anything" autofocus/>
 </div>
</div>
</div>
</div>
</div>