config/routes.rb
Rails.application.routes.draw do
  
  resources :conversations, only: [:show]
  
  get 'chat', to: 'conversations#retrieve_conversation', as: 'chat'
  
  post 'reminder', to: 'emails#reminder', as: 'reminder'
  
  post 'update_rating', to: 'saved_links#update_rating', as: 'update_rating'
  
  resources :saved_links, only: [:index]

  get 'update_link', to: 'saved_links#update_link', as: 'update_link'
  
  get 'posts/test'

  get 'posts/test_yaml'

  resources :appointments

  get "my_clients", to: 'appointments#my_clients', as: 'my_clients'
  get 'my_appointments', to: 'appointments#my_appointments', as: 'my_appointments'

  get 'search', to: 'search#results', as: 'search'

  get 'contact/new'

  post 'contact/send_email'

  post 'tokens' => "tokens#create"

  get 'my_answers', to: 'answers#my_answers', as: 'my_answers'

  resources :messages

  resources :answers

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :posts

  get 'my_posts', to: 'posts#my_posts', as: 'my_posts'

 get 'auth/:provider/callback', to: 'sessions#create'

 get 'sign_out', to: 'sessions#destroy', as: 'sign_out'

 post 'send', to: 'messages#email_message', as: 'mail'

  root 'posts#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
# realtionships
belongs_to :user
belongs_to :consultant, class_name: "User"


 validates :name, presence: true
 validates :email, presence: true
 validates :time, presence: true
 validates_uniqueness_of :time
 
  
  

  def start_time
  	time
  end
 
 # get all the appointments for the following day
 def self.following_day_appointments
  all.where("time >= ?", (Time.now + 3.hours))
 end

end

app/models/chat_message.rb
class ChatMessage < ActiveRecord::Base
  # associations
  belongs_to :conversation
  belongs_to :user
  
  #life cycle hook
  after_create_commit { ChatMessageBroadcastJob.perform_later self }
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  	#associations
  	belongs_to :user
  	belongs_to :consultant, class_name: "User"
  	has_many :chat_messages, dependent: :destroy
  	
  	#validations
  	validates_uniqueness_of :user_id, scope: :consultant_id
  	
end

app/models/data.rb
require 'result'
class Data
	def self.parse(results)
		result_set = []
		results.items.each do |result|
			
			# item = SavedLink.find_by_link_url(result.link.to_s) ? SavedLink.find_by_link_url(result.link.to_s) : Result.new(result.title, result.link.to_s)
			if SavedLink.find_by_link_url(result.link.to_s)
				link = SavedLink.find_by_link_url(result.link.to_s)
				item = Result.new(link.title, link.link_url, link.click_count, link.average_rating, link.ratings.count.to_i)
				result_set << item
			else
				item = Result.new(result.title.to_s, result.link.to_s)
				result_set << item
			end
		end
		result_set # return the result set
	end
	
	def self.sort(results)
		results.sort_by! {|object| [object.average_rating, object.number_of_ratings, object.click_count] }
		results.reverse!
	end
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :description, presence: true
	
    belongs_to :user
    has_many :answers

end

app/models/rating.rb
class Rating < ActiveRecord::Base
    belongs_to :saved_link
    
    VALUES = [1, 2, 3, 4, 5]
end

app/models/result.rb
require 'data'
class Result
	attr_accessor :title, :link_url, :click_count, :average_rating, :number_of_ratings

	def initialize(title, link_url, click_count = 0, average_rating = 0, number_of_ratings = 0)
		@title = title
		@link_url = link_url
		@click_count = click_count
		@average_rating = average_rating
		@number_of_ratings = number_of_ratings
	end
end

app/models/saved_link.rb
class SavedLink < ActiveRecord::Base
    has_many :ratings
    
    def sum_of_ratings
        ratings.pluck(:rating).inject(0) {|sum, number| sum += number}
    end
    
    def average_rating
        sum_of_ratings/ratings.count.to_d
    end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	has_many :answers
	has_many :appointments
	has_many :clients, class_name: "Appointment", foreign_key: "consultant_id" 
	has_many :conversations
	has_many :chat_messages

	ROLES = ["admin", "consultant", "user"]

	def self.create_with_omniauth(auth)
		create! do |user|
		user.provider = auth["provider"]
		user.uid = auth["uid"]
		user.name = auth["info"]["name"]
		user.email = auth["info"]["email"]
		end
	end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :check_current_user_is_signed_in
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  
  def my_answers
      @answers = Answer.where(user_id: current_user.id).order(created_at: :desc)
  end
  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
    if request.xhr?
    respond_to do |format|
      format.html
      format.js
    end
    end
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to posts_path, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: posts_path }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   
   def check_current_user_is_signed_in
      unless current_user_signed_in?
        redirect_to root_url, notice: "Please sign in to do that"
      end
    end

    def current_user_signed_in?
        current_user ? true : false
    end

  
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

     def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
     end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:description, :user_id, :post_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
 <div class="form-style-9">
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="field">
    <% f.hidden_field :post_id, value: nil %>
  </div>
  <div class="actions">
    <%= f.submit "Post Reply", class: "small button round" %>
  </div>
<% end %>
</div>

app/views/answers/edit.html.erb
<h1 style="text-align: center">Editing answer</h1>

<div class="large-12 columns"> 

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>
</div>

app/views/answers/index.html.erb
<h1 style="text-align: center">Listing answers</h1>

<div class="large-12 columns"> 
 <div class="form-style-10">
 <% @answers.each do |answer| %>
   <p> User: <%= answer.user_id %></p>
   <p> Answer: <%= answer.description %></p>
    <ul class="inline-list">
      <li><%= link_to 'Show', answer %></li>
      <li><%= link_to 'Edit', edit_answer_path(answer) %></li>
      <li><%= button_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></li>
    </ul>
  <hr/>
<% end %>
</div>



<%= link_to 'New Answer', new_answer_path %>
</div>

app/views/answers/my_answers.html.erb
<div class="row">
<div class="large-12 columns">
 <h2 style="text-align: center">My Answers</h2> 
 <div class="form-style-10">

 	<% @answers.each do |answer| %>
   <h1><%= answer.user.name unless answer.user_id.nil? %> | <%= answer.created_at.strftime("%e %b %Y") %> </h1>
    <div class="inner-wrap"> Answer: <%= answer.description unless answer.description.nil? %></div>
    
 
    <%= link_to truncate(answer.post.description, length: 80), post_path(answer.post) unless answer.post_id.nil? %>
   

  	<hr/>
	<% end %>

</div>
</div>
</div>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/new.js.erb
$('#reply_link').html("<%= j (render partial: 'layouts/reply', locals: {post: post}) %>");

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @answer.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user_id %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>