config/routes.rb
Rails.application.routes.draw do
  
  resources :conversations, only: [:show]
  
  get 'chat', to: 'conversations#retrieve_conversation', as: 'chat'
  
  post 'reminder', to: 'emails#reminder', as: 'reminder'
  
  post 'update_rating', to: 'saved_links#update_rating', as: 'update_rating'
  
  resources :saved_links, only: [:index]

  get 'update_link', to: 'saved_links#update_link', as: 'update_link'
  
  get 'posts/test'

  get 'posts/test_yaml'

  resources :appointments

  get "my_clients", to: 'appointments#my_clients', as: 'my_clients'
  get 'my_appointments', to: 'appointments#my_appointments', as: 'my_appointments'

  get 'search', to: 'search#results', as: 'search'

  get 'contact/new'

  post 'contact/send_email'

  post 'tokens' => "tokens#create"

  get 'my_answers', to: 'answers#my_answers', as: 'my_answers'

  resources :messages

  resources :answers

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :posts

  get 'my_posts', to: 'posts#my_posts', as: 'my_posts'

 get 'auth/:provider/callback', to: 'sessions#create'

 get 'sign_out', to: 'sessions#destroy', as: 'sign_out'

 post 'send', to: 'messages#email_message', as: 'mail'

  root 'posts#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
# realtionships
belongs_to :user
belongs_to :consultant, class_name: "User"


 validates :name, presence: true
 validates :email, presence: true
 validates :time, presence: true
 validates_uniqueness_of :time
 
  
  

  def start_time
  	time
  end
 
 # get all the appointments for the following day
 def self.following_day_appointments
  all.where("time >= ?", (Time.now + 3.hours))
 end

end

app/models/chat_message.rb
class ChatMessage < ActiveRecord::Base
  # associations
  belongs_to :conversation
  belongs_to :user
  
  #life cycle hook
  after_create_commit { ChatMessageBroadcastJob.perform_later self }
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  	#associations
  	belongs_to :user
  	belongs_to :consultant, class_name: "User"
  	has_many :chat_messages, dependent: :destroy
  	
  	#validations
  	validates_uniqueness_of :user_id, scope: :consultant_id
  	
end

app/models/data.rb
require 'result'
class Data
	def self.parse(results)
		result_set = []
		results.items.each do |result|
			
			# item = SavedLink.find_by_link_url(result.link.to_s) ? SavedLink.find_by_link_url(result.link.to_s) : Result.new(result.title, result.link.to_s)
			if SavedLink.find_by_link_url(result.link.to_s)
				link = SavedLink.find_by_link_url(result.link.to_s)
				item = Result.new(link.title, link.link_url, link.click_count, link.average_rating, link.ratings.count.to_i)
				result_set << item
			else
				item = Result.new(result.title.to_s, result.link.to_s)
				result_set << item
			end
		end
		result_set # return the result set
	end
	
	def self.sort(results)
		results.sort_by! {|object| [object.average_rating, object.number_of_ratings, object.click_count] }
		results.reverse!
	end
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :description, presence: true
	
    belongs_to :user
    has_many :answers

end

app/models/rating.rb
class Rating < ActiveRecord::Base
    belongs_to :saved_link
    
    VALUES = [1, 2, 3, 4, 5]
end

app/models/result.rb
require 'data'
class Result
	attr_accessor :title, :link_url, :click_count, :average_rating, :number_of_ratings

	def initialize(title, link_url, click_count = 0, average_rating = 0, number_of_ratings = 0)
		@title = title
		@link_url = link_url
		@click_count = click_count
		@average_rating = average_rating
		@number_of_ratings = number_of_ratings
	end
end

app/models/saved_link.rb
class SavedLink < ActiveRecord::Base
    has_many :ratings
    
    def sum_of_ratings
        ratings.pluck(:rating).inject(0) {|sum, number| sum += number}
    end
    
    def average_rating
        sum_of_ratings/ratings.count.to_d
    end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	has_many :answers
	has_many :appointments
	has_many :clients, class_name: "Appointment", foreign_key: "consultant_id" 
	has_many :conversations
	has_many :chat_messages

	ROLES = ["admin", "consultant", "user"]

	def self.create_with_omniauth(auth)
		create! do |user|
		user.provider = auth["provider"]
		user.uid = auth["uid"]
		user.name = auth["info"]["name"]
		user.email = auth["info"]["email"]
		end
	end
end

app/controllers/posts_controller.rb
require 'data'
require 'result'
class PostsController < ApplicationController
  # include CurrentUser
  # before_action :set_current_user
  before_action :check_current_user_is_signed_in, except: [:index]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :suggestions]

  def my_posts
    @posts = Post.where(user_id: current_user.id).order(created_at: :desc)
  end

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
    

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
   @answer = Answer.new
   @results = GoogleCustomSearchApi.search(@post.description.to_s)
   @result_list = Data.parse(@results)
   @results_list = Data.sort(@result_list)
  end

  def test_yaml
    @results = GoogleCustomSearchApi.search("Viet Nam holiday")
  end

  def test
    @results = GoogleCustomSearchApi.search("Raspberry Pi")
    @result_list = Data.parse(@results)
    @results_list = Data.sort(@result_list)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def check_current_user_is_signed_in
      unless current_user_signed_in?
        redirect_to root_url, notice: "Please sign in to do that"
      end
    end

    def current_user_signed_in?
        current_user ? true : false
    end

    # def current_user
    # @current_user ||= User.find(session[:user_id]) if session[:user_id]
    # end
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :user_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<div class="form-style-10">
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>-->
  <div class="field">
    <h2><%= f.label :description, {:style=>'color:#257C9E; font-size:14px', :class => "css_class"} %></h2>
    <%= f.text_area :description, rows: 3 %>
     
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'small button round' %>
  </div>
<% end %>
</div>

app/views/posts/_post.html.erb

<div class="col-lg-12">
  
    <div class="form-style-10">

        <h1><%= post.description %>
        <span><%= post.created_at.strftime("%e %b %Y") %>  

        <% if current_user %>
            <% if post.user.nil? %>
            <%= "No User" %>
            <% elsif post.user != current_user %>
            <%= "Anonymous" %>
            <% else %>
            <%= post.user.name %>
            <% end %>
        <% end %>
       </span>
       </h1>
    
      <!--<div class="inner-wrap"><%= post.description %></div>-->
       

        <% if current_user %>
        <% if current_user.role == 'user' %>
        <div class="inline-list">
          <%= link_to image_tag("file_edit.png", :size => "40x40", :crop => :fill), edit_post_path(post) %>
          <%= button_to 'Destroy', post, method: :delete, class: "button small round" %>
         
        </div>
        <% end %>
        <% end %>
        
        <!-- Reply Box for Consultants only-->
        <% if current_user %>
        <% if current_user.role == 'consultant' %>
        <%= button_to "Write a Reply", post, method: :get, class: 'small button round' %>
        <% end %>
        <% end %>
    

        <% if post.answers.any? %>
          <div class="section"><span><%= post.answers.count %></span> Answers</div>
          <% post.answers.order(created_at: :desc).each do |answer| %>


          <!--Answer box  -->

        <div class="row">
          <div class="col-xs-1">
              <% if answer.user %>
                <% if current_user %>
                  <% if current_user == answer.user %>
                  <%= link_to image_tag("chat.png", size: "45x45", crop: :fill), chat_path(user_id: current_user.id, consultant_id: answer.user.id) , alt: "chat to consultant" %>
                  <%= answer.user.name %>
                  
                  <% else %>
                   
                    <%= link_to image_tag("message.png", :size => "45x45", :crop => :fill), contact_new_path(consultant_email: answer.user.email), alt: "Email Consultant" %>
                     <%= link_to image_tag("calendar.png", :size => "45x45", :crop => :fill), new_appointment_path(consultant_id: answer.user.id) %>
                     <%= link_to image_tag("chat.png", size: "45x45", crop: :fill), chat_path(user_id: current_user.id, consultant_id: answer.user.id) , alt: "chat to consultant" %>
                  <% end %>  
                  <% end %>
              <% else %>
                <%= link_to "No consultant", "#" %>
              <% end %>
          </div>  
          <div class="col-xs-11">
            <div class="inner-wrap">
              <p><%= answer.description %></p>
              <p style="text-align: right"><%= answer.created_at.strftime("%e %b %Y") %><br>
            </div>
          </div>
        </div>
          
          <br />
      <% end %>
      <% end %>
       </div>
  
  </div>


  




app/views/posts/edit.html.erb
<div class="row">
<div class="col-lg-12">
<div class="form-style-8">
<h1 style="text-align: center; color:#257C9E">Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post, {:style=>'color:#257C9E;', :class => "css_class"} %> |
<%= link_to 'Back to My Posts', my_posts_path, {:style=>'color:#257C9E;', :class => "css_class"} %> |
<%= link_to 'Back to All Posts', posts_path, {:style=>'color:#257C9E;', :class => "css_class"} %>
</div>
</di>
</div>

app/views/posts/index.html.erb
<div class="container-fluid">
<div class="row">
    <div class="col-lg-12">
       
        <!-- Search bar -->
        <!--<div class="form-style-10">-->
        <!--     <%= form_tag(posts_path, :method => "get", id: "search-form") do %>-->
        <!--    <%= text_field_tag :search, params[:search], placeholder: "Search for problem" %>-->
        <!--    <%= submit_tag "Search", class: 'small button round' %>-->
        <!--    <% end %>-->
        <!--</div>-->
      
     <%= render @posts %>
  </div>
</div>
</div>


  

app/views/posts/my_posts.html.erb
<div class="row">
<div class="large-12 columns"> 
<h2 style="text-align: center">My Posts</h2>
     <%= render @posts %>
  </div>
 </div>



app/views/posts/new.html.erb
<div class="row">
<div class="large-12 columns">
	<div class="form-style-10">
	<h2 style="text-align: center; color:#257C9E">Post Your Problem</h2>
	
		
		<%= render 'form' %>

		<%= link_to image_tag("Back.png", :size => "50x50", :crop => :fill), posts_path %>
	</div>
</div>
</div>

app/views/posts/show.html.erb
<div class="row">
<div class="large-12 columns">
<p id="notice"><%= notice %></p>


<!--<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>-->
 <!--Show a created post  -->

<div class="form-style-10">
<h1><strong>Your Problem:</strong> <%= @post.description %> </h1>

<% if current_user.role == 'consultant' %>
<%= form_for(@answer) do |f| %>
  
	 <div class="field">
	    <%= f.text_area :description, rows: 4 %>
	 </div>
	 <div class="field">
	    <%= f.hidden_field :user_id, value: current_user.id %>
	 </div>
	 <div class=”field”>
		<%= f.hidden_field :post_id, value: @post.id %>
	 </div>

	 <div class=”field”>
	    <%= f.submit "Post Answer" %>
	 </div>
<% end %>
<% end %>

<br />


<% if @post.answers.any? %>

	<h2 style="text-align: center; color:#257C9E">Answers</h2>
		<% @post.answers.each do |answer| %>
		 <div class="inner-wrap">
      <p><%= answer.description %></p>
			<p style="text-align: right"><%= answer.user.name %> - <%= answer.created_at.strftime("%e %b %Y") %></p>
			
		</div>
		<% end %>
	
<% end %>

<!--This is the link to go back my answer if user is consultant and back to all post if -->
<%= link_to image_tag("file_edit.png", :size => "20x20", :crop => :fill), edit_post_path(@post) %> |
<% if current_user.role == 'consultant' %>
<%= link_to 'Back to My Answers', my_answers_path, {:style=>'color:#257C9E;', :class => "css_class"} %> |
<%= link_to 'Back to All Posts', posts_path, {:style=>'color:#257C9E;', :class => "css_class"}%>
<% else %>
<%= link_to 'Back to All Posts', posts_path, {:style=>'color:#257C9E;', :class => "css_class"} %>
<% end %>
</div>



 <!--Show suggestions following user's problem   -->
<% if current_user.role == 'user' %>
<div class="form-style-10">
<h2 style="text-align: center; color:#257C9E"><%= @results_list.length %> Suggestions</h2>
<% @results_list.each do |item| %>
    <%= render partial: "results/result", locals: {result: item} %>
  <% end %>
  <% end %>
</div>
</div>
</div>

app/views/posts/show.js.erb
$('#reply_link').html("<%= escape_javascript( render partial: 'layouts/reply', locals: {post: post}) %>");

app/views/posts/test.html.erb
<div>
	<h3>Results with partial and object</h3>
	<h5>Is array? <%= @results_list.kind_of?(Array) %></h5>
	<br>
	<%= @results_list.each do |result| %>
	<%= render partial: "results/result", locals: {result: result}  %>
	<% end %>
</div>

app/views/posts/test_yaml.html.erb
<%= @results.to_yaml %>